# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Cell App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for Cell App

  target 'Cell AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cell AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
